import type { Metadata } from 'next'
import { Header } from '@/widgets/header'
import { Provider } from '@/shared/provider'
import './globals.css'
import { headers } from 'next/headers'
import { checkAuthOnServer } from '@/entities/auth/lib/checkAuthOnServer'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
	title: 'GortopGram - Социальная сеть',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const pathname = await headers()
	const path = pathname.get('x-pathname')
	const isAuth = await checkAuthOnServer()

	const showHeader = isAuth || path !== '/'

	return (
		<Provider>
			<html lang='ru'>
				<body>
					{showHeader && <Header />}
					<main>{children}</main>
					<ToastContainer position='bottom-right' />
				</body>
			</html>
		</Provider>
	)
}
